# Generated by Django 5.2.6 on 2025-09-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='preferences',
            field=models.TextField(blank=True, help_text='e.g Residential, Commercial', null=True),
        ),
    ]
