# Generated by Django 5.2.6 on 2025-09-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('architect', 'Architect'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
