# Generated by Django 5.2.6 on 2025-09-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('architect', 'Architect'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
