# Generated by Django 5.2.6 on 2025-09-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('architect', 'Architect')], default='client', max_length=20),
        ),
    ]
