# Generated by Django 5.2.6 on 2025-09-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('architect', 'Architect'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
